### ISSUE TITLE
Fix WorkItemTypeDeniedOrNotExistException in Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItem.get_Type

### ISSUE THREAD

**Issue by flcdrg** [flcdrg/XsltCop#96]
### Reason ###

Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemTypeDeniedOrNotExistException: TF201077: The work item type  cannot be found. It may have been renamed or destroyed.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/365518/crash_reasons/157556145](https://rink.hockeyapp.net/manage/apps/365518/crash_reasons/157556145)

**Comment by tacho090** [comment]
what was the fix?

**Comment by flcdrg** [comment]
This was incorrectly captured by HockeyApp logging. I'm going to delete this issue to avoid confusion.
